"""Scoped local AI knowledge, conversations and automation receipts.

Revision ID: 0057_local_ai
Revises: 0056_host_terminal
"""
import sqlalchemy as sa
from alembic import op

revision = "0057_local_ai"
down_revision = "0056_host_terminal"
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('learning_enabled', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_prompts',
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('ai_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('automation_id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=150), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=120), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('automation_id', 'event_key', name='uq_ai_rule_event')
    )
    op.create_index(op.f('ix_ai_runs_automation_id'), 'ai_runs', ['automation_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_state'), 'ai_runs', ['state'], unique=False)
    op.create_table('ai_scripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('tested_revision', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_events',
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.Float(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_ai_events_park_id'), 'ai_events', ['park_id'], unique=False)
    op.create_index(op.f('ix_ai_events_processed'), 'ai_events', ['processed'], unique=False)
    op.create_table('ai_automations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('enabled_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_automations_park_id'), 'ai_automations', ['park_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_owner_id'), 'ai_conversations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_park_id'), 'ai_conversations', ['park_id'], unique=False)
    op.create_table('ai_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('trust', sa.String(length=20), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('source_ref', sa.String(length=400), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_index(op.f('ix_ai_documents_fingerprint'), 'ai_documents', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_ai_documents_park_id'), 'ai_documents', ['park_id'], unique=False)
    op.create_index(op.f('ix_ai_documents_state'), 'ai_documents', ['state'], unique=False)
    op.create_table('ai_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ai_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chunks_document_id'), 'ai_chunks', ['document_id'], unique=False)
    op.create_table('ai_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_ai_job_key')
    )
    op.create_index('ix_ai_jobs_due', 'ai_jobs', ['state', 'created_at'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('ai_terms',
    sa.Column('term', sa.String(length=80), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['ai_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('term', 'chunk_id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('ai_terms')
    op.drop_table('ai_messages')
    op.drop_table('ai_jobs')
    op.drop_table('ai_chunks')
    op.drop_table('ai_documents')
    op.drop_table('ai_conversations')
    op.drop_table('ai_automations')
    op.drop_table('ai_events')
    op.drop_table('ai_scripts')
    op.drop_table('ai_runs')
    op.drop_table('ai_prompts')
    op.drop_table('ai_connectors')
    op.drop_table('ai_config')
